# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Img(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, base64: str=None):  # noqa: E501
        """Img - a model defined in Swagger

        :param base64: The base64 of this Img.  # noqa: E501
        :type base64: str
        """
        self.swagger_types = {
            'base64': str
        }

        self.attribute_map = {
            'base64': 'base64'
        }
        self._base64 = base64

    @classmethod
    def from_dict(cls, dikt) -> 'Img':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Img of this Img.  # noqa: E501
        :rtype: Img
        """
        return util.deserialize_model(dikt, cls)

    @property
    def base64(self) -> str:
        """Gets the base64 of this Img.


        :return: The base64 of this Img.
        :rtype: str
        """
        return self._base64

    @base64.setter
    def base64(self, base64: str):
        """Sets the base64 of this Img.


        :param base64: The base64 of this Img.
        :type base64: str
        """

        self._base64 = base64
