# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InputFichierGeneration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, inference_chemin_absolu: str=None, param_chemin_absolu: str=None):  # noqa: E501
        """InputFichierGeneration - a model defined in Swagger

        :param inference_chemin_absolu: The inference_chemin_absolu of this InputFichierGeneration.  # noqa: E501
        :type inference_chemin_absolu: str
        :param param_chemin_absolu: The param_chemin_absolu of this InputFichierGeneration.  # noqa: E501
        :type param_chemin_absolu: str
        """
        self.swagger_types = {
            'inference_chemin_absolu': str,
            'param_chemin_absolu': str
        }

        self.attribute_map = {
            'inference_chemin_absolu': 'inference_chemin_absolu',
            'param_chemin_absolu': 'param_chemin_absolu'
        }
        self._inference_chemin_absolu = inference_chemin_absolu
        self._param_chemin_absolu = param_chemin_absolu

    @classmethod
    def from_dict(cls, dikt) -> 'InputFichierGeneration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InputFichierGeneration of this InputFichierGeneration.  # noqa: E501
        :rtype: InputFichierGeneration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def inference_chemin_absolu(self) -> str:
        """Gets the inference_chemin_absolu of this InputFichierGeneration.


        :return: The inference_chemin_absolu of this InputFichierGeneration.
        :rtype: str
        """
        return self._inference_chemin_absolu

    @inference_chemin_absolu.setter
    def inference_chemin_absolu(self, inference_chemin_absolu: str):
        """Sets the inference_chemin_absolu of this InputFichierGeneration.


        :param inference_chemin_absolu: The inference_chemin_absolu of this InputFichierGeneration.
        :type inference_chemin_absolu: str
        """

        self._inference_chemin_absolu = inference_chemin_absolu

    @property
    def param_chemin_absolu(self) -> str:
        """Gets the param_chemin_absolu of this InputFichierGeneration.


        :return: The param_chemin_absolu of this InputFichierGeneration.
        :rtype: str
        """
        return self._param_chemin_absolu

    @param_chemin_absolu.setter
    def param_chemin_absolu(self, param_chemin_absolu: str):
        """Sets the param_chemin_absolu of this InputFichierGeneration.


        :param param_chemin_absolu: The param_chemin_absolu of this InputFichierGeneration.
        :type param_chemin_absolu: str
        """

        self._param_chemin_absolu = param_chemin_absolu
